import { EMPLOYEE_COUNT_QUESTION } from './employeeCount.ts'
import type { ExperienceQuestion } from './types.ts'

export const RETIRED_QUESTION_CODES = new Set([
  'analysis_units',
  'maturity',
  'control_method',
  'main_objective',
  'primary_activity',
  'activities',
  'tech_costs',
  'hlt_costs',
  'min_costs',
  'media_costs',
  'agro_hectares',
  'agro_productivity',
  'agro_estimated_production',
  'agro_avg_price',
  'pec_buy_sell',
  'tracks_unit_costs',
  'agro_tracks_cost_hectare',
  'agro_tracks_cost_crop',
  'agro_tracks_productivity_hectare',
  'agro_track_arroba_like',
  'pec_tracks_lot',
  'pec_tracks_animal',
  'pec_wants_arroba',
  'com_stock',
  'ind_stock_rm',
  'ind_stock_fg',
  'auto_stock',
  'pro_hours',
  'ind_costs',
  'con_costs',
  'food_costs',
  'srv_costs',
  'hlt_volume',
  're_costs',
  'eng_costs',
  'beau_costs',
  'mkt_costs',
  'env_costs',
  'pec_animals',
  'pec_properties',
  'pec_lots',
  'pec_area',
  'pec_avg_weight',
  'pec_arroba',
  'pec_milk',
  'pec_cost_animal',
  'pec_costs',
  'fish_volume',
  'fish_area',
  'com_type',
  'com_stores',
  'com_categories',
  'com_ticket',
  'com_volume',
  'com_costs',
  'ind_volume',
  'ind_capacity',
  'ind_inputs',
  'con_works',
  'con_area',
  'con_value',
  'con_deadline',
  'trn_vehicles',
  'trn_km',
  'trn_trips',
  'trn_capacity',
  'trn_tons',
  'trn_costs',
  'food_units',
  'food_orders',
  'food_ticket',
  'srv_clients',
  'srv_contracts',
  'srv_projects',
  'srv_hours',
  'srv_avg_contract',
  'tech_clients',
  'tech_users',
  'tech_projects',
  'tech_hours',
  'hlt_units',
  'hlt_pros',
  'edu_students',
  'edu_courses',
  'edu_classes',
  'edu_teachers',
  'edu_tuition',
  're_properties',
  're_contracts',
  're_avg_value',
  'auto_vehicles',
  'auto_ticket',
  'eng_capacity',
  'eng_units',
  'eng_production',
  'min_area',
  'min_volume',
  'hot_rooms',
  'hot_capacity',
  'hot_occupancy',
  'hot_rate',
  'beau_pros',
  'beau_attendances',
  'beau_ticket',
  'media_clients',
  'media_projects',
  'mkt_clients',
  'mkt_projects',
  'ent_events',
  'ent_capacity',
  'ent_ticket',
  'spt_clients',
  'spt_ticket',
  'env_projects',
  'env_volume',
  'fin_clients',
  'fin_contracts',
  'pro_clients',
  'pub_units',
  'oth_costs',
])

export const RETIRED_QUESTION_PROMPTS = new Set([
  'A empresa compra e vende animais com frequência?',
  'Você acompanha seus custos por unidade?',
  'A empresa acompanha custo por hectare?',
  'Você acompanha o custo individual por cultura?',
  'Você acompanha produtividade por hectare?',
  'Você deseja acompanhar o custo por saca?',
  'Você controla o custo por lote?',
  'Você controla o custo por animal?',
  'Você deseja acompanhar o custo por arroba?',
  'A empresa controla estoque?',
  'A empresa controla estoque de matéria-prima?',
  'A empresa controla estoque de produtos acabados?',
  'A empresa controla estoque de peças?',
  'As horas trabalhadas são controladas?',
  'Quais custos de produção você acompanha?',
  'Quais custos você acompanha por obra?',
  'Quais custos você quer acompanhar?',
  'Quais custos por projeto são acompanhados?',
  'O que a empresa acompanha no atendimento?',
  'Quais custos você acompanha por imóvel?',
  'Quais custos operacionais são acompanhados?',
  'Quais custos você acompanha?',
  'Como você avalia a maturidade do controle financeiro?',
  'Como a empresa controla as finanças hoje?',
  'Qual é o objetivo principal ao usar a plataforma?',
  'Qual é a atividade principal da empresa?',
  'Quais custos são mais relevantes?',
  'Quais atividades a empresa realiza?',
  'Qual é o tipo de comércio?',
  'Qual é a quantidade aproximada de produtos?',
  'Qual é a produtividade média?',
  'Quais categorias de produtos são mais relevantes?',
  'Qual é a quantidade de lotes?',
  'Qual é o ticket médio?',
  'Qual é a área utilizada (hectares)?',
  'Qual é o volume médio de vendas?',
  'Qual é a produção estimada?',
  'Qual é o peso médio dos animais?',
  'Quais custos pesam mais nas vendas?',
  'Qual é a produção de arrobas?',
  'Qual é o custo médio por animal?',
  'Quantos hectares são utilizados?',
  'Qual é o preço médio de venda?',
  'Qual é a quantidade de animais?',
  'Quantas propriedades a empresa utiliza?',
  'Qual é a produção de leite?',
  'Quais custos são mais importantes para sua atividade?',
  'Qual é o volume produzido?',
  'Qual é a área ou lâmina d’água utilizada?',
  'Quantas lojas a empresa possui?',
  'Qual é o volume de produção?',
  'Qual é a capacidade produtiva?',
  'Quais matérias-primas são mais relevantes?',
  'Quantas obras estão ativas?',
  'Qual é a área construída (m²)?',
  'Qual é o valor contratado?',
  'Qual é o prazo médio das obras (meses)?',
  'Qual é a quantidade de veículos?',
  'Qual é a quilometragem média?',
  'Qual é a quantidade de viagens?',
  'Qual é a capacidade de carga?',
  'Quantas toneladas são transportadas?',
  'Quais custos são mais importantes?',
  'Quantas unidades a empresa possui?',
  'Qual é o número médio de pedidos?',
  'Qual é a quantidade de clientes?',
  'Qual é a quantidade de contratos?',
  'Quantos projetos são realizados?',
  'Qual é o volume de horas trabalhadas?',
  'Qual é o valor médio dos contratos?',
  'Qual é o número de clientes?',
  'Qual é o número de usuários?',
  'Quantos projetos estão ativos?',
  'Quantos profissionais atuam na operação?',
  'Qual é o número de alunos?',
  'Quantos cursos são oferecidos?',
  'Quantas turmas estão ativas?',
  'Quantos professores atuam na instituição?',
  'Qual é a mensalidade média?',
  'Qual é a quantidade de imóveis?',
  'Qual é o valor médio dos imóveis?',
  'Quantos veículos são atendidos?',
  'Qual é a capacidade instalada?',
  'Quantas unidades fazem parte da operação?',
  'Qual é a produção (kWh)?',
  'Qual é a área explorada?',
  'Qual é o volume extraído?',
  'Qual é o número de quartos?',
  'Qual é a capacidade de hóspedes?',
  'Qual é a taxa média de ocupação (%)?',
  'Qual é a diária média?',
  'Quantos profissionais atuam no negócio?',
  'Qual é o número de atendimentos?',
  'Quantos clientes a empresa atende?',
  'Quantos projetos ou campanhas estão ativos?',
  'Quantos clientes a agência atende?',
  'Qual é o número de eventos?',
  'Qual é a capacidade do espaço?',
  'Qual é o número de clientes ou alunos?',
  'Qual é o volume processado?',
  'Quantas unidades administrativas existem?',
])

export function isRetiredQuestion(question: ExperienceQuestion): boolean {
  if (RETIRED_QUESTION_CODES.has(question.code)) return true
  if (RETIRED_QUESTION_PROMPTS.has(question.prompt)) return true
  if (question.answerType === 'number' && question.code !== EMPLOYEE_COUNT_QUESTION) {
    return true
  }
  return false
}
