insert into public.analysis_units (code, name, description, applicable_segments)
select v.code, v.name, v.description, v.segments
from (
  values
    ('hectare', 'Hectare', 'Área produtiva', array['agro','livestock','fishing']),
    ('bag', 'Saca', 'Produção em sacas', array['agro']),
    ('ton', 'Tonelada', 'Volume em toneladas', array['agro','industry','mining','fishing','environment']),
    ('crop', 'Cultura', 'Cultura agrícola', array['agro']),
    ('animal', 'Animal', 'Animal individual', array['livestock']),
    ('head', 'Cabeça', 'Cabeça de gado', array['livestock']),
    ('arroba', 'Arroba', 'Produção em arrobas', array['livestock']),
    ('lot', 'Lote', 'Lote de animais ou produção', array['livestock','industry']),
    ('product', 'Produto', 'Produto comercializado ou fabricado', array['commerce','industry','food','automotive']),
    ('sold_unit', 'Unidade vendida', 'Unidade vendida', array['commerce']),
    ('category', 'Categoria', 'Categoria de produtos', array['commerce']),
    ('store', 'Loja', 'Unidade comercial', array['commerce','food','beauty']),
    ('produced_unit', 'Unidade produzida', 'Unidade fabricada', array['industry']),
    ('km', 'Km', 'Quilômetro rodado', array['transport_logistics']),
    ('trip', 'Viagem', 'Viagem realizada', array['transport_logistics']),
    ('vehicle', 'Veículo', 'Veículo da operação', array['transport_logistics','automotive']),
    ('transported_ton', 'Tonelada transportada', 'Carga transportada', array['transport_logistics']),
    ('work', 'Obra', 'Obra ou empreendimento', array['construction']),
    ('sqm', 'm²', 'Metro quadrado construído', array['construction']),
    ('work_stage', 'Etapa da obra', 'Etapa construtiva', array['construction']),
    ('client', 'Cliente', 'Cliente atendido', array['services','professional','financial','tech','media','marketing','environment','food']),
    ('project', 'Projeto', 'Projeto realizado', array['services','professional','tech','media','marketing','environment']),
    ('contract', 'Contrato', 'Contrato vigente', array['services','professional','financial','tech','real_estate']),
    ('worked_hour', 'Hora trabalhada', 'Hora de trabalho', array['services','professional','tech','media','marketing','automotive','beauty']),
    ('user', 'Usuário', 'Usuário da plataforma', array['tech']),
    ('meal', 'Refeição', 'Refeição servida', array['food']),
    ('order', 'Pedido', 'Pedido realizado', array['food']),
    ('appointment', 'Consulta', 'Consulta realizada', array['health']),
    ('procedure', 'Procedimento', 'Procedimento realizado', array['health']),
    ('patient', 'Paciente', 'Paciente atendido', array['health']),
    ('student', 'Aluno', 'Aluno matriculado', array['education']),
    ('class_group', 'Turma', 'Turma', array['education']),
    ('course', 'Curso', 'Curso oferecido', array['education']),
    ('property', 'Imóvel', 'Imóvel administrado', array['real_estate']),
    ('service', 'Serviço', 'Serviço realizado', array['automotive','beauty','services','professional']),
    ('kwh', 'kWh', 'Energia produzida ou consumida', array['energy']),
    ('extracted_unit', 'Unidade extraída', 'Unidade mineral extraída', array['mining']),
    ('room', 'Quarto', 'Unidade habitacional', array['hospitality']),
    ('guest', 'Hóspede', 'Hóspede atendido', array['hospitality']),
    ('reservation', 'Reserva', 'Reserva realizada', array['hospitality']),
    ('attendance', 'Atendimento', 'Atendimento realizado', array['beauty']),
    ('professional', 'Profissional', 'Profissional da operação', array['beauty','health']),
    ('campaign', 'Campanha', 'Campanha de mídia ou marketing', array['media','marketing']),
    ('event', 'Evento', 'Evento realizado', array['entertainment','sports']),
    ('employee', 'Funcionário', 'Colaborador', array['agro','livestock','fishing','commerce','industry','construction','services','tech','transport_logistics','food','hospitality','health','education','real_estate','financial','automotive','energy','mining','media','marketing','entertainment','sports','beauty','professional','environment','public_admin','other'])
) as v(code, name, description, segments)
on conflict (code) do update
set
  name = excluded.name,
  description = excluded.description,
  applicable_segments = excluded.applicable_segments,
  is_active = true;
