-- Indicadores do modelo de operação + pergunta de prioridades.

update public.onboarding_questions
set
  question = 'Qual é o modelo de operação?',
  options = '[{"value":"operacao_propria","label":"Operação própria"},{"value":"operacao_arrendada","label":"Operação arrendada"},{"value":"operacao_terceirizada","label":"Operação terceirizada"},{"value":"operacao_mista","label":"Operação mista"},{"value":"franquia","label":"Franquia"}]'::jsonb,
  is_active = true
where code = 'operation_model';

insert into public.onboarding_questions (
  code, question, help_text, answer_type, options, sort_order, maps_to,
  is_active, is_optional, option_source, show_when
) values (
  'operation_priorities',
  'Selecione quais informações são mais importantes para sua empresa?',
  'Marque os indicadores do seu modelo de operação. Eles aparecem em Indicadores operacionais e podem ser alterados depois no perfil da empresa.',
  'multiple',
  '[]'::jsonb,
  75,
  'fact.operation_priorities',
  true,
  true,
  'operation_indicators',
  '{"in":{"answer":"operation_model","values":["operacao_propria","propria","própria","operacao_arrendada","arrendada","operacao_terceirizada","terceirizada","operacao_mista","mista","franquia"]}}'::jsonb
)
on conflict (code) do update
set
  question = excluded.question,
  help_text = excluded.help_text,
  answer_type = excluded.answer_type,
  options = excluded.options,
  sort_order = excluded.sort_order,
  maps_to = excluded.maps_to,
  is_active = true,
  is_optional = true,
  option_source = excluded.option_source,
  show_when = excluded.show_when;

insert into public.system_indicators (
  code, name, description, formula_hint, formula, category, unit,
  applicable_segments, activation_conditions, unless_conditions,
  required_data, periodicity, dashboard_section, sort_order, is_active
) values
(
    'own_total_operating_cost',
    'Custo operacional total',
    'Soma dos custos e despesas realizados da operação própria no período.',
    'custos + despesas realizados',
    'custos + despesas realizados',
    'operational',
    'R$',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_propria","propria","própria"]}},{"eq":{"answer":"operation_priorities","value":"own_total_operating_cost"}}]}'::jsonb,
    null,
    '[]'::jsonb,
    'monthly',
    'operational',
    4000,
    true
  ),
(
    'own_cost_per_produced_unit',
    'Custo por unidade produzida',
    'Custo operacional total dividido pelas unidades produzidas.',
    'custo operacional total / unidades produzidas',
    'custo operacional total / unidades produzidas',
    'operational',
    'R$/un',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_propria","propria","própria"]}},{"eq":{"answer":"operation_priorities","value":"own_cost_per_produced_unit"}}]}'::jsonb,
    null,
    '["units_produced"]'::jsonb,
    'monthly',
    'operational',
    4010,
    true
  ),
(
    'own_operating_margin',
    'Margem operacional',
    'Lucro operacional em relação à receita do período.',
    '(receita − custos) / receita',
    '(receita − custos) / receita',
    'operational',
    '%',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_propria","propria","própria"]}},{"eq":{"answer":"operation_priorities","value":"own_operating_margin"}}]}'::jsonb,
    null,
    '[]'::jsonb,
    'monthly',
    'operational',
    4020,
    true
  ),
(
    'own_roa',
    'ROA',
    'Retorno sobre os ativos: lucro do período dividido pelo valor dos ativos.',
    'lucro / ativos totais',
    'lucro / ativos totais',
    'operational',
    '%',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_propria","propria","própria"]}},{"eq":{"answer":"operation_priorities","value":"own_roa"}}]}'::jsonb,
    null,
    '["total_assets"]'::jsonb,
    'monthly',
    'operational',
    4030,
    true
  ),
(
    'own_roi',
    'ROI',
    'Retorno sobre o investimento: lucro do período dividido pelo capital investido.',
    'lucro / capital investido',
    'lucro / capital investido',
    'operational',
    '%',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_propria","propria","própria"]}},{"eq":{"answer":"operation_priorities","value":"own_roi"}}]}'::jsonb,
    null,
    '["investment"]'::jsonb,
    'monthly',
    'operational',
    4040,
    true
  ),
(
    'own_break_even',
    'Ponto de equilíbrio',
    'Receita necessária para cobrir os custos fixos com a margem de contribuição atual.',
    'custos fixos / margem de contribuição %',
    'custos fixos / margem de contribuição %',
    'operational',
    'R$',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_propria","propria","própria"]}},{"eq":{"answer":"operation_priorities","value":"own_break_even"}}]}'::jsonb,
    null,
    '["fixed_costs"]'::jsonb,
    'monthly',
    'operational',
    4050,
    true
  ),
(
    'own_asset_idle',
    'Ociosidade dos ativos',
    'Percentual da capacidade que ficou ociosa no período.',
    'capacidade ociosa / capacidade total',
    'capacidade ociosa / capacidade total',
    'operational',
    '%',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_propria","propria","própria"]}},{"eq":{"answer":"operation_priorities","value":"own_asset_idle"}}]}'::jsonb,
    null,
    '["idle_capacity","total_capacity"]'::jsonb,
    'monthly',
    'operational',
    4060,
    true
  ),
(
    'own_maintenance_per_asset',
    'Custo de manutenção por ativo',
    'Custo de manutenção dividido pela quantidade de ativos.',
    'manutenção / quantidade de ativos',
    'manutenção / quantidade de ativos',
    'operational',
    'R$/ativo',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_propria","propria","própria"]}},{"eq":{"answer":"operation_priorities","value":"own_maintenance_per_asset"}}]}'::jsonb,
    null,
    '["maintenance_cost","asset_count"]'::jsonb,
    'monthly',
    'operational',
    4070,
    true
  ),
(
    'own_depreciation_per_unit',
    'Custo de depreciação por unidade',
    'Depreciação do período dividida pelas unidades produzidas.',
    'depreciação / unidades produzidas',
    'depreciação / unidades produzidas',
    'operational',
    'R$/un',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_propria","propria","própria"]}},{"eq":{"answer":"operation_priorities","value":"own_depreciation_per_unit"}}]}'::jsonb,
    null,
    '["depreciation","units_produced"]'::jsonb,
    'monthly',
    'operational',
    4080,
    true
  ),
(
    'own_productivity_per_asset',
    'Produtividade por ativo',
    'Unidades produzidas por ativo utilizado.',
    'unidades produzidas / quantidade de ativos',
    'unidades produzidas / quantidade de ativos',
    'operational',
    'un/ativo',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_propria","propria","própria"]}},{"eq":{"answer":"operation_priorities","value":"own_productivity_per_asset"}}]}'::jsonb,
    null,
    '["units_produced","asset_count"]'::jsonb,
    'monthly',
    'operational',
    4090,
    true
  ),
(
    'lease_cost',
    'Custo de arrendamento',
    'Valor pago pelo arrendamento no período.',
    'custo de arrendamento informado',
    'custo de arrendamento informado',
    'operational',
    'R$',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_arrendada","arrendada"]}},{"eq":{"answer":"operation_priorities","value":"lease_cost"}}]}'::jsonb,
    null,
    '["lease_cost"]'::jsonb,
    'monthly',
    'operational',
    4200,
    true
  ),
(
    'lease_cost_per_unit',
    'Custo de arrendamento por unidade',
    'Arrendamento dividido pela área ou quantidade de unidades arrendadas.',
    'custo de arrendamento / área ou unidades',
    'custo de arrendamento / área ou unidades',
    'operational',
    'R$/un',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_arrendada","arrendada"]}},{"eq":{"answer":"operation_priorities","value":"lease_cost_per_unit"}}]}'::jsonb,
    null,
    '["lease_cost","leased_units"]'::jsonb,
    'monthly',
    'operational',
    4210,
    true
  ),
(
    'lease_total_operating_cost',
    'Custo operacional total',
    'Soma dos custos e despesas realizados, incluindo o arrendamento lançado no extrato.',
    'custos + despesas realizados',
    'custos + despesas realizados',
    'operational',
    'R$',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_arrendada","arrendada"]}},{"eq":{"answer":"operation_priorities","value":"lease_total_operating_cost"}}]}'::jsonb,
    null,
    '[]'::jsonb,
    'monthly',
    'operational',
    4220,
    true
  ),
(
    'lease_margin_after',
    'Margem após arrendamento',
    'Resultado depois dos custos realizados, já considerando o arrendamento do extrato.',
    '(receita − custos) / receita',
    '(receita − custos) / receita',
    'operational',
    '%',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_arrendada","arrendada"]}},{"eq":{"answer":"operation_priorities","value":"lease_margin_after"}}]}'::jsonb,
    null,
    '[]'::jsonb,
    'monthly',
    'operational',
    4230,
    true
  ),
(
    'lease_area_return',
    'Rentabilidade da área/ativo arrendado',
    'Lucro do período dividido pelo valor da área ou do ativo arrendado.',
    'lucro / valor do ativo ou área arrendada',
    'lucro / valor do ativo ou área arrendada',
    'operational',
    '%',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_arrendada","arrendada"]}},{"eq":{"answer":"operation_priorities","value":"lease_area_return"}}]}'::jsonb,
    null,
    '["leased_asset_value"]'::jsonb,
    'monthly',
    'operational',
    4240,
    true
  ),
(
    'lease_revenue_per_unit',
    'Receita por área/unidade',
    'Receita do período dividida pela área ou quantidade arrendada.',
    'receita / área ou unidades arrendadas',
    'receita / área ou unidades arrendadas',
    'operational',
    'R$/un',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_arrendada","arrendada"]}},{"eq":{"answer":"operation_priorities","value":"lease_revenue_per_unit"}}]}'::jsonb,
    null,
    '["leased_units"]'::jsonb,
    'monthly',
    'operational',
    4250,
    true
  ),
(
    'lease_profit_per_unit',
    'Lucro por área/unidade',
    'Lucro do período dividido pela área ou quantidade arrendada.',
    'lucro / área ou unidades arrendadas',
    'lucro / área ou unidades arrendadas',
    'operational',
    'R$/un',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_arrendada","arrendada"]}},{"eq":{"answer":"operation_priorities","value":"lease_profit_per_unit"}}]}'::jsonb,
    null,
    '["leased_units"]'::jsonb,
    'monthly',
    'operational',
    4260,
    true
  ),
(
    'lease_break_even',
    'Ponto de equilíbrio do arrendamento',
    'Receita necessária para cobrir o arrendamento com a margem de contribuição atual.',
    'custo de arrendamento / margem de contribuição %',
    'custo de arrendamento / margem de contribuição %',
    'operational',
    'R$',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_arrendada","arrendada"]}},{"eq":{"answer":"operation_priorities","value":"lease_break_even"}}]}'::jsonb,
    null,
    '["lease_cost"]'::jsonb,
    'monthly',
    'operational',
    4270,
    true
  ),
(
    'lease_vs_own_cost',
    'Custo de arrendar × custo de possuir',
    'Razão entre o custo de arrendar e o custo de possuir o mesmo ativo.',
    'custo de arrendamento / custo de possuir',
    'custo de arrendamento / custo de possuir',
    'operational',
    'x',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_arrendada","arrendada"]}},{"eq":{"answer":"operation_priorities","value":"lease_vs_own_cost"}}]}'::jsonb,
    null,
    '["lease_cost","ownership_cost"]'::jsonb,
    'monthly',
    'operational',
    4280,
    true
  ),
(
    'lease_return_on_area',
    'Retorno sobre área arrendada',
    'Lucro do período dividido pela área arrendada.',
    'lucro / área arrendada',
    'lucro / área arrendada',
    'operational',
    'R$/área',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_arrendada","arrendada"]}},{"eq":{"answer":"operation_priorities","value":"lease_return_on_area"}}]}'::jsonb,
    null,
    '["leased_area"]'::jsonb,
    'monthly',
    'operational',
    4290,
    true
  ),
(
    'out_cost',
    'Custo de terceirização',
    'Valor pago a terceiros pela operação no período.',
    'custo de terceirização informado',
    'custo de terceirização informado',
    'operational',
    'R$',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_terceirizada","terceirizada"]}},{"eq":{"answer":"operation_priorities","value":"out_cost"}}]}'::jsonb,
    null,
    '["outsourcing_cost"]'::jsonb,
    'monthly',
    'operational',
    4400,
    true
  ),
(
    'out_cost_per_unit',
    'Custo terceirizado por unidade',
    'Custo de terceirização dividido pelas unidades da operação terceirizada.',
    'custo de terceirização / unidades',
    'custo de terceirização / unidades',
    'operational',
    'R$/un',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_terceirizada","terceirizada"]}},{"eq":{"answer":"operation_priorities","value":"out_cost_per_unit"}}]}'::jsonb,
    null,
    '["outsourcing_cost","outsourced_units"]'::jsonb,
    'monthly',
    'operational',
    4410,
    true
  ),
(
    'out_operation_share',
    '% da operação terceirizada',
    'Participação da terceirização no custo operacional total realizado.',
    'custo de terceirização / custo operacional total',
    'custo de terceirização / custo operacional total',
    'operational',
    '%',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_terceirizada","terceirizada"]}},{"eq":{"answer":"operation_priorities","value":"out_operation_share"}}]}'::jsonb,
    null,
    '["outsourcing_cost"]'::jsonb,
    'monthly',
    'operational',
    4420,
    true
  ),
(
    'out_vs_internal_cost',
    'Custo terceirizado × custo interno',
    'Razão entre o custo terceirizado e o custo interno comparável.',
    'custo de terceirização / custo interno',
    'custo de terceirização / custo interno',
    'operational',
    'x',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_terceirizada","terceirizada"]}},{"eq":{"answer":"operation_priorities","value":"out_vs_internal_cost"}}]}'::jsonb,
    null,
    '["outsourcing_cost","internal_cost"]'::jsonb,
    'monthly',
    'operational',
    4430,
    true
  ),
(
    'out_savings',
    'Economia com terceirização',
    'Diferença entre o custo interno comparável e o custo de terceirização.',
    'custo interno − custo de terceirização',
    'custo interno − custo de terceirização',
    'operational',
    'R$',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_terceirizada","terceirizada"]}},{"eq":{"answer":"operation_priorities","value":"out_savings"}}]}'::jsonb,
    null,
    '["internal_cost","outsourcing_cost"]'::jsonb,
    'monthly',
    'operational',
    4440,
    true
  ),
(
    'out_margin_after',
    'Margem após terceirização',
    'Resultado depois dos custos realizados, já considerando a terceirização do extrato.',
    '(receita − custos) / receita',
    '(receita − custos) / receita',
    'operational',
    '%',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_terceirizada","terceirizada"]}},{"eq":{"answer":"operation_priorities","value":"out_margin_after"}}]}'::jsonb,
    null,
    '[]'::jsonb,
    'monthly',
    'operational',
    4450,
    true
  ),
(
    'out_cost_per_service',
    'Custo por serviço contratado',
    'Custo de terceirização dividido pelos serviços contratados.',
    'custo de terceirização / serviços contratados',
    'custo de terceirização / serviços contratados',
    'operational',
    'R$/serviço',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_terceirizada","terceirizada"]}},{"eq":{"answer":"operation_priorities","value":"out_cost_per_service"}}]}'::jsonb,
    null,
    '["outsourcing_cost","contracted_services"]'::jsonb,
    'monthly',
    'operational',
    4460,
    true
  ),
(
    'out_third_party_productivity',
    'Produtividade do terceiro',
    'Unidades entregues por terceiro que atuou na operação.',
    'unidades entregues / quantidade de terceiros',
    'unidades entregues / quantidade de terceiros',
    'operational',
    'un/terceiro',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_terceirizada","terceirizada"]}},{"eq":{"answer":"operation_priorities","value":"out_third_party_productivity"}}]}'::jsonb,
    null,
    '["delivered_units","third_party_count"]'::jsonb,
    'monthly',
    'operational',
    4470,
    true
  ),
(
    'out_cost_per_delivered',
    'Custo por unidade entregue',
    'Custo de terceirização dividido pelas unidades entregues.',
    'custo de terceirização / unidades entregues',
    'custo de terceirização / unidades entregues',
    'operational',
    'R$/un',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_terceirizada","terceirizada"]}},{"eq":{"answer":"operation_priorities","value":"out_cost_per_delivered"}}]}'::jsonb,
    null,
    '["outsourcing_cost","delivered_units"]'::jsonb,
    'monthly',
    'operational',
    4480,
    true
  ),
(
    'out_dependency',
    'Dependência de terceiros',
    'Peso da terceirização sobre o custo terceirizado mais o custo interno comparável.',
    'custo de terceirização / (terceirização + custo interno)',
    'custo de terceirização / (terceirização + custo interno)',
    'operational',
    '%',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_terceirizada","terceirizada"]}},{"eq":{"answer":"operation_priorities","value":"out_dependency"}}]}'::jsonb,
    null,
    '["outsourcing_cost","internal_cost"]'::jsonb,
    'monthly',
    'operational',
    4490,
    true
  ),
(
    'mix_cost_by_model',
    'Custo por modelo de operação',
    'Custos da operação própria, arrendada e terceirizada no período.',
    'custo próprio + arrendado + terceirizado',
    'custo próprio + arrendado + terceirizado',
    'operational',
    'R$',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_mista","mista"]}},{"eq":{"answer":"operation_priorities","value":"mix_cost_by_model"}}]}'::jsonb,
    null,
    '["own_cost","lease_cost","out_cost"]'::jsonb,
    'monthly',
    'operational',
    4600,
    true
  ),
(
    'mix_cost_per_unit_by_model',
    'Custo por unidade por modelo',
    'Custo unitário de cada modelo e o custo médio ponderado da operação.',
    'custo total dos modelos / unidades totais',
    'custo total dos modelos / unidades totais',
    'operational',
    'R$/un',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_mista","mista"]}},{"eq":{"answer":"operation_priorities","value":"mix_cost_per_unit_by_model"}}]}'::jsonb,
    null,
    '["own_cost","lease_cost","out_cost","own_units","lease_units","out_units"]'::jsonb,
    'monthly',
    'operational',
    4610,
    true
  ),
(
    'mix_cost_share',
    'Participação de cada modelo nos custos',
    'Peso de cada modelo no custo total da operação mista.',
    'custo do modelo / custo total dos modelos',
    'custo do modelo / custo total dos modelos',
    'operational',
    '%',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_mista","mista"]}},{"eq":{"answer":"operation_priorities","value":"mix_cost_share"}}]}'::jsonb,
    null,
    '["own_cost","lease_cost","out_cost"]'::jsonb,
    'monthly',
    'operational',
    4620,
    true
  ),
(
    'mix_margin_by_model',
    'Margem por modelo',
    'Margem de cada modelo e a margem consolidada da operação mista.',
    'lucro dos modelos / receita dos modelos',
    'lucro dos modelos / receita dos modelos',
    'operational',
    '%',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_mista","mista"]}},{"eq":{"answer":"operation_priorities","value":"mix_margin_by_model"}}]}'::jsonb,
    null,
    '["own_revenue","lease_revenue","out_revenue","own_cost","lease_cost","out_cost"]'::jsonb,
    'monthly',
    'operational',
    4630,
    true
  ),
(
    'mix_return_by_model',
    'Rentabilidade por modelo',
    'Lucro de cada modelo em relação ao investimento alocado.',
    'lucro dos modelos / investimento dos modelos',
    'lucro dos modelos / investimento dos modelos',
    'operational',
    '%',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_mista","mista"]}},{"eq":{"answer":"operation_priorities","value":"mix_return_by_model"}}]}'::jsonb,
    null,
    '["own_revenue","lease_revenue","out_revenue","own_cost","lease_cost","out_cost","own_investment","lease_investment","out_investment"]'::jsonb,
    'monthly',
    'operational',
    4640,
    true
  ),
(
    'mix_revenue_by_model',
    'Receita por modelo',
    'Receita gerada por cada modelo de operação.',
    'receita própria + arrendada + terceirizada',
    'receita própria + arrendada + terceirizada',
    'operational',
    'R$',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_mista","mista"]}},{"eq":{"answer":"operation_priorities","value":"mix_revenue_by_model"}}]}'::jsonb,
    null,
    '["own_revenue","lease_revenue","out_revenue"]'::jsonb,
    'monthly',
    'operational',
    4650,
    true
  ),
(
    'mix_profit_by_model',
    'Lucro por modelo',
    'Resultado de cada modelo: receita menos custo informado.',
    '(receita − custo) de cada modelo',
    '(receita − custo) de cada modelo',
    'operational',
    'R$',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_mista","mista"]}},{"eq":{"answer":"operation_priorities","value":"mix_profit_by_model"}}]}'::jsonb,
    null,
    '["own_revenue","lease_revenue","out_revenue","own_cost","lease_cost","out_cost"]'::jsonb,
    'monthly',
    'operational',
    4660,
    true
  ),
(
    'mix_productivity_by_model',
    'Produtividade por modelo',
    'Volume produzido por cada modelo de operação.',
    'unidades próprias + arrendadas + terceirizadas',
    'unidades próprias + arrendadas + terceirizadas',
    'operational',
    'un',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_mista","mista"]}},{"eq":{"answer":"operation_priorities","value":"mix_productivity_by_model"}}]}'::jsonb,
    null,
    '["own_units","lease_units","out_units"]'::jsonb,
    'monthly',
    'operational',
    4670,
    true
  ),
(
    'mix_weighted_avg_cost',
    'Custo médio ponderado da operação',
    'Custo total dos modelos dividido pelo volume total produzido.',
    'custo total dos modelos / unidades totais',
    'custo total dos modelos / unidades totais',
    'operational',
    'R$/un',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_mista","mista"]}},{"eq":{"answer":"operation_priorities","value":"mix_weighted_avg_cost"}}]}'::jsonb,
    null,
    '["own_cost","lease_cost","out_cost","own_units","lease_units","out_units"]'::jsonb,
    'monthly',
    'operational',
    4680,
    true
  ),
(
    'mix_savings_between',
    'Economia entre modelos',
    'Diferença entre o maior e o menor custo por unidade dos modelos preenchidos.',
    'maior custo unitário − menor custo unitário',
    'maior custo unitário − menor custo unitário',
    'operational',
    'R$/un',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_mista","mista"]}},{"eq":{"answer":"operation_priorities","value":"mix_savings_between"}}]}'::jsonb,
    null,
    '["own_cost","lease_cost","out_cost","own_units","lease_units","out_units"]'::jsonb,
    'monthly',
    'operational',
    4690,
    true
  ),
(
    'mix_roi_by_model',
    'ROI por modelo',
    'Retorno sobre o investimento de cada modelo e o consolidado.',
    'lucro dos modelos / investimento dos modelos',
    'lucro dos modelos / investimento dos modelos',
    'operational',
    '%',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_mista","mista"]}},{"eq":{"answer":"operation_priorities","value":"mix_roi_by_model"}}]}'::jsonb,
    null,
    '["own_revenue","lease_revenue","out_revenue","own_cost","lease_cost","out_cost","own_investment","lease_investment","out_investment"]'::jsonb,
    'monthly',
    'operational',
    4700,
    true
  ),
(
    'mix_break_even_by_model',
    'Ponto de equilíbrio por modelo',
    'Receita necessária para cobrir os custos fixos de cada modelo.',
    'custos fixos do modelo / margem de contribuição %',
    'custos fixos do modelo / margem de contribuição %',
    'operational',
    'R$',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["operacao_mista","mista"]}},{"eq":{"answer":"operation_priorities","value":"mix_break_even_by_model"}}]}'::jsonb,
    null,
    '["own_fixed","lease_fixed","out_fixed","own_cost","lease_cost","out_cost","own_revenue","lease_revenue","out_revenue"]'::jsonb,
    'monthly',
    'operational',
    4710,
    true
  ),
(
    'fr_unit_revenue',
    'Faturamento da unidade',
    'Receita realizada da unidade no período.',
    'soma das receitas',
    'soma das receitas',
    'operational',
    'R$',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["franquia"]}},{"eq":{"answer":"operation_priorities","value":"fr_unit_revenue"}}]}'::jsonb,
    null,
    '[]'::jsonb,
    'monthly',
    'operational',
    4800,
    true
  ),
(
    'fr_avg_ticket',
    'Ticket médio',
    'Faturamento dividido pelo número de vendas do período.',
    'faturamento / vendas',
    'faturamento / vendas',
    'operational',
    'R$',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["franquia"]}},{"eq":{"answer":"operation_priorities","value":"fr_avg_ticket"}}]}'::jsonb,
    null,
    '["sales_count"]'::jsonb,
    'monthly',
    'operational',
    4810,
    true
  ),
(
    'fr_gross_margin',
    'Margem bruta',
    'Faturamento menos CMV, em relação ao faturamento.',
    '(faturamento − CMV) / faturamento',
    '(faturamento − CMV) / faturamento',
    'operational',
    '%',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["franquia"]}},{"eq":{"answer":"operation_priorities","value":"fr_gross_margin"}}]}'::jsonb,
    null,
    '["cogs"]'::jsonb,
    'monthly',
    'operational',
    4820,
    true
  ),
(
    'fr_operating_margin',
    'Margem operacional',
    'Resultado operacional da unidade sobre o faturamento.',
    '(receita − custos) / receita',
    '(receita − custos) / receita',
    'operational',
    '%',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["franquia"]}},{"eq":{"answer":"operation_priorities","value":"fr_operating_margin"}}]}'::jsonb,
    null,
    '[]'::jsonb,
    'monthly',
    'operational',
    4830,
    true
  ),
(
    'fr_royalties',
    'Royalties sobre faturamento',
    'Alíquota de royalties aplicada sobre o faturamento da unidade.',
    'faturamento × alíquota de royalties',
    'faturamento × alíquota de royalties',
    'operational',
    'R$',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["franquia"]}},{"eq":{"answer":"operation_priorities","value":"fr_royalties"}}]}'::jsonb,
    null,
    '["royalty_rate"]'::jsonb,
    'monthly',
    'operational',
    4840,
    true
  ),
(
    'fr_franchise_fee',
    'Taxa de franquia',
    'Taxa de franquia paga no período.',
    'taxa de franquia informada',
    'taxa de franquia informada',
    'operational',
    'R$',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["franquia"]}},{"eq":{"answer":"operation_priorities","value":"fr_franchise_fee"}}]}'::jsonb,
    null,
    '["franchise_fee"]'::jsonb,
    'monthly',
    'operational',
    4850,
    true
  ),
(
    'fr_ad_fee',
    'Taxa de publicidade',
    'Percentual de publicidade aplicado sobre o faturamento.',
    'faturamento × taxa de publicidade',
    'faturamento × taxa de publicidade',
    'operational',
    'R$',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["franquia"]}},{"eq":{"answer":"operation_priorities","value":"fr_ad_fee"}}]}'::jsonb,
    null,
    '["ad_rate"]'::jsonb,
    'monthly',
    'operational',
    4860,
    true
  ),
(
    'fr_operating_cost_per_unit',
    'Custo operacional por unidade',
    'Custo realizado dividido pelas unidades da franquia acompanhadas.',
    'custo operacional / unidades da franquia',
    'custo operacional / unidades da franquia',
    'operational',
    'R$/un',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["franquia"]}},{"eq":{"answer":"operation_priorities","value":"fr_operating_cost_per_unit"}}]}'::jsonb,
    null,
    '["franchise_units"]'::jsonb,
    'monthly',
    'operational',
    4870,
    true
  ),
(
    'fr_net_profit',
    'Lucro líquido da unidade',
    'Receita menos custos e despesas realizados da unidade.',
    'receita − custos − despesas',
    'receita − custos − despesas',
    'operational',
    'R$',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["franquia"]}},{"eq":{"answer":"operation_priorities","value":"fr_net_profit"}}]}'::jsonb,
    null,
    '[]'::jsonb,
    'monthly',
    'operational',
    4880,
    true
  ),
(
    'fr_payback',
    'Payback do investimento',
    'Meses necessários para recuperar o investimento com o lucro atual.',
    'investimento / lucro do período',
    'investimento / lucro do período',
    'operational',
    'meses',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["franquia"]}},{"eq":{"answer":"operation_priorities","value":"fr_payback"}}]}'::jsonb,
    null,
    '["franchise_investment"]'::jsonb,
    'monthly',
    'operational',
    4890,
    true
  ),
(
    'fr_roi',
    'ROI da franquia',
    'Lucro da unidade dividido pelo investimento na franquia.',
    'lucro / investimento',
    'lucro / investimento',
    'operational',
    '%',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["franquia"]}},{"eq":{"answer":"operation_priorities","value":"fr_roi"}}]}'::jsonb,
    null,
    '["franchise_investment"]'::jsonb,
    'monthly',
    'operational',
    4900,
    true
  ),
(
    'fr_break_even',
    'Ponto de equilíbrio',
    'Faturamento necessário para cobrir os custos fixos da unidade.',
    'custos fixos / margem de contribuição %',
    'custos fixos / margem de contribuição %',
    'operational',
    'R$',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["franquia"]}},{"eq":{"answer":"operation_priorities","value":"fr_break_even"}}]}'::jsonb,
    null,
    '["fixed_costs"]'::jsonb,
    'monthly',
    'operational',
    4910,
    true
  ),
(
    'fr_revenue_per_employee',
    'Faturamento por funcionário',
    'Receita da unidade dividida pelo quadro de funcionários da empresa.',
    'faturamento / funcionários',
    'faturamento / funcionários',
    'operational',
    'R$/funcionário',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["franquia"]}},{"eq":{"answer":"operation_priorities","value":"fr_revenue_per_employee"}}]}'::jsonb,
    null,
    '[]'::jsonb,
    'monthly',
    'operational',
    4920,
    true
  ),
(
    'fr_revenue_per_sqm',
    'Faturamento por m²',
    'Receita da unidade dividida pela área em metros quadrados.',
    'faturamento / m²',
    'faturamento / m²',
    'operational',
    'R$/m²',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["franquia"]}},{"eq":{"answer":"operation_priorities","value":"fr_revenue_per_sqm"}}]}'::jsonb,
    null,
    '["sqm"]'::jsonb,
    'monthly',
    'operational',
    4930,
    true
  ),
(
    'fr_sales_count',
    'Vendas por período',
    'Quantidade de vendas realizadas pela unidade no período.',
    'quantidade de vendas informada',
    'quantidade de vendas informada',
    'operational',
    'un',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["franquia"]}},{"eq":{"answer":"operation_priorities","value":"fr_sales_count"}}]}'::jsonb,
    null,
    '["sales_count"]'::jsonb,
    'monthly',
    'operational',
    4940,
    true
  ),
(
    'fr_growth_rate',
    'Taxa de crescimento',
    'Variação do faturamento em relação ao período anterior.',
    '(faturamento atual − anterior) / anterior',
    '(faturamento atual − anterior) / anterior',
    'operational',
    '%',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["franquia"]}},{"eq":{"answer":"operation_priorities","value":"fr_growth_rate"}}]}'::jsonb,
    null,
    '[]'::jsonb,
    'monthly',
    'operational',
    4950,
    true
  ),
(
    'fr_cac',
    'CAC',
    'Custo de aquisição de cliente: marketing dividido pelos novos clientes.',
    'custo de aquisição / novos clientes',
    'custo de aquisição / novos clientes',
    'operational',
    'R$',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["franquia"]}},{"eq":{"answer":"operation_priorities","value":"fr_cac"}}]}'::jsonb,
    null,
    '["marketing_cost","new_customers"]'::jsonb,
    'monthly',
    'operational',
    4960,
    true
  ),
(
    'fr_ltv',
    'LTV',
    'Valor do tempo de vida do cliente: receita por cliente vezes a vida média em meses.',
    '(faturamento / clientes) × vida média em meses',
    '(faturamento / clientes) × vida média em meses',
    'operational',
    'R$',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["franquia"]}},{"eq":{"answer":"operation_priorities","value":"fr_ltv"}}]}'::jsonb,
    null,
    '["customer_count","lifespan_months"]'::jsonb,
    'monthly',
    'operational',
    4970,
    true
  ),
(
    'fr_margin_after_royalties',
    'Margem após royalties',
    'Resultado depois dos custos realizados e dos royalties calculados sobre o faturamento.',
    '(lucro − royalties) / receita',
    '(lucro − royalties) / receita',
    'operational',
    '%',
    null,
    '{"all":[{"in":{"answer":"operation_model","values":["franquia"]}},{"eq":{"answer":"operation_priorities","value":"fr_margin_after_royalties"}}]}'::jsonb,
    null,
    '["royalty_rate"]'::jsonb,
    'monthly',
    'operational',
    4980,
    true
  )
on conflict (code) do update
set
  name = excluded.name,
  description = excluded.description,
  formula_hint = excluded.formula_hint,
  formula = excluded.formula,
  category = excluded.category,
  unit = excluded.unit,
  applicable_segments = excluded.applicable_segments,
  activation_conditions = excluded.activation_conditions,
  unless_conditions = excluded.unless_conditions,
  required_data = excluded.required_data,
  dashboard_section = excluded.dashboard_section,
  sort_order = excluded.sort_order,
  is_active = true;

